#!/usr/bin/env Rscript
# ==============================================================================
# Script: 05_analyze_biotin_thresholds_and_status.R
# Authors: Alfredo Pherez-Farah (ORCID: 0000-0003-2213-3405); Willem de Koning (ORCID: 0000-0002-4594-8423)
# Manuscript provenance: Panel 1G was made by ranking biotin delta at sample level.
# Purpose: Compute cluster-specific biotin thresholds, assign biotin status, summarize biotin enrichment, and run treated-only pseudobulk DGE.
# Inputs: Processed Seurat object with RNA and ADT assays, final cluster labels, condition labels, and sample IDs.
# Outputs: PNG plots, Excel summaries, and CSV/DGE tables.
# Dependencies: Seurat, ggplot2, dplyr, tidyr, openxlsx, edgeR, EnhancedVolcano.
# Environment: Main analysis environment (conda + renv).
# Notes:
# - Edit the configuration section before running.
# - Results are generated by this script and are not stored in the repository.
# ==============================================================================

suppressPackageStartupMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(openxlsx)
  library(edgeR)
  library(EnhancedVolcano)
})

set.seed(1)

# ------------------------------------------------------------------------------
# 1. CONFIGURATION  ← EDIT THIS SECTION
# ------------------------------------------------------------------------------

input_file <- "path/to/combined_seurat_normalized.rds"
output_dir <- "path/to/biotin_analysis"

cluster_column <- "final_clusters"
condition_column <- "condition"
sample_column <- "hash.ID"

rna_assay <- "RNA"
adt_assay <- "ADT"
biotin_feature <- "Biotin-TotalSeqC"

treated_label <- "treated"
untreated_label <- "untreated"

min_untreated_cells_for_threshold <- 5
threshold_quantile <- 0.75

min_pos_cells_treated <- 50
min_pct_pos_treated <- 35

clusters_of_interest <- c("0", "1", "2", "4", "7", "8", "9", "13", "14")

run_pseudobulk_dge <- TRUE
dge_min_samples_with_both_statuses <- 2
volcano_p_cutoff <- 0.05
volcano_fc_cutoff <- 0.5

# ------------------------------------------------------------------------------
# 2. HELPER FUNCTIONS
# ------------------------------------------------------------------------------

make_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  path
}

save_png <- function(plot, filename, width = 7, height = 5, dpi = 300) {
  ggsave(filename, plot = plot, width = width, height = height, dpi = dpi)
}

has_assay <- function(object, assay_name) {
  assay_name %in% Assays(object)
}

require_metadata <- function(object, columns) {
  missing_columns <- setdiff(columns, colnames(object@meta.data))
  if (length(missing_columns) > 0) {
    stop("Missing required metadata columns: ", paste(missing_columns, collapse = ", "))
  }
}

write_xlsx <- function(tables, filename) {
  wb <- createWorkbook()

  for (sheet_name in names(tables)) {
    addWorksheet(wb, sheet_name)
    writeData(wb, sheet_name, tables[[sheet_name]])
  }

  saveWorkbook(wb, filename, overwrite = TRUE)
}

get_biotin_values <- function(object, cells, adt_assay, biotin_feature) {
  GetAssayData(object, assay = adt_assay, slot = "data")[biotin_feature, cells, drop = TRUE]
}

safe_numeric_sort <- function(x) {
  x[order(suppressWarnings(as.numeric(as.character(x))))]
}

# ------------------------------------------------------------------------------
# 3. LOAD DATA AND VALIDATE INPUTS
# ------------------------------------------------------------------------------

if (!file.exists(input_file)) {
  stop("Input file does not exist: ", input_file)
}

output_dir <- make_dir(output_dir)
threshold_dir <- make_dir(file.path(output_dir, "thresholds"))
summary_dir <- make_dir(file.path(output_dir, "summaries"))
plot_dir <- make_dir(file.path(output_dir, "plots"))
dge_dir <- make_dir(file.path(output_dir, "pseudobulk_edgeR"))
volcano_dir <- make_dir(file.path(dge_dir, "volcano_plots"))

seurat_object <- readRDS(input_file)

require_metadata(
  seurat_object,
  c(cluster_column, condition_column, sample_column)
)

if (!has_assay(seurat_object, rna_assay)) {
  stop("RNA assay not found: ", rna_assay)
}

if (!has_assay(seurat_object, adt_assay)) {
  stop("ADT assay not found: ", adt_assay)
}

if (!biotin_feature %in% rownames(seurat_object[[adt_assay]])) {
  stop("Biotin feature not found in ADT assay: ", biotin_feature)
}

seurat_object[[cluster_column]] <- as.character(seurat_object[[cluster_column]][, 1])
Idents(seurat_object) <- seurat_object[[cluster_column]][, 1]

DefaultAssay(seurat_object) <- adt_assay

message("Loaded Seurat object with ", ncol(seurat_object), " cells.")
message("Using ADT feature: ", biotin_feature)

# ------------------------------------------------------------------------------
# 4. COMPUTE CLUSTER-SPECIFIC BIOTIN THRESHOLDS
# ------------------------------------------------------------------------------

clusters <- safe_numeric_sort(unique(seurat_object@meta.data[[cluster_column]]))

threshold_table <- lapply(clusters, function(cluster_id) {
  cells_untreated <- rownames(seurat_object@meta.data)[
    seurat_object@meta.data[[cluster_column]] == cluster_id &
      seurat_object@meta.data[[condition_column]] == untreated_label
  ]

  n_untreated <- length(cells_untreated)

  threshold <- NA_real_

  if (n_untreated >= min_untreated_cells_for_threshold) {
    values <- get_biotin_values(
      object = seurat_object,
      cells = cells_untreated,
      adt_assay = adt_assay,
      biotin_feature = biotin_feature
    )

    threshold <- as.numeric(
      quantile(values, threshold_quantile, na.rm = TRUE)
    )
  }

  data.frame(
    cluster = cluster_id,
    n_untreated = n_untreated,
    threshold_quantile = threshold_quantile,
    biotin_threshold = threshold
  )
}) %>%
  bind_rows()

write.csv(
  threshold_table,
  file.path(threshold_dir, "biotin_thresholds_by_cluster.csv"),
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 5. ASSIGN BIOTIN STATUS
# ------------------------------------------------------------------------------

biotin_status <- rep(NA_character_, ncol(seurat_object))
names(biotin_status) <- colnames(seurat_object)

thresholds <- setNames(
  threshold_table$biotin_threshold,
  threshold_table$cluster
)

for (cluster_id in names(thresholds)) {
  threshold <- thresholds[[cluster_id]]

  if (is.na(threshold)) {
    next
  }

  cells_cluster <- rownames(seurat_object@meta.data)[
    seurat_object@meta.data[[cluster_column]] == cluster_id
  ]

  if (length(cells_cluster) == 0) {
    next
  }

  values <- get_biotin_values(
    object = seurat_object,
    cells = cells_cluster,
    adt_assay = adt_assay,
    biotin_feature = biotin_feature
  )

  biotin_status[names(values)] <- ifelse(values > threshold, "positive", "negative")
}

seurat_object$biotin_status <- factor(
  biotin_status,
  levels = c("negative", "positive")
)

status_table <- seurat_object@meta.data %>%
  count(.data[[cluster_column]], biotin_status, name = "n") %>%
  rename(cluster = .data[[cluster_column]])

write.csv(
  status_table,
  file.path(summary_dir, "biotin_status_counts_by_cluster.csv"),
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 6. VIOLIN PLOTS BY CLUSTER
# ------------------------------------------------------------------------------

for (cluster_id in clusters) {
  cells_cluster <- rownames(seurat_object@meta.data)[
    seurat_object@meta.data[[cluster_column]] == cluster_id
  ]

  if (length(cells_cluster) == 0) {
    next
  }

  threshold <- thresholds[[cluster_id]]

  p <- VlnPlot(
    seurat_object,
    features = biotin_feature,
    assay = adt_assay,
    group.by = condition_column,
    cells = cells_cluster,
    pt.size = 0.2
  ) +
    ggtitle(paste0("Cluster ", cluster_id, " - ", biotin_feature)) +
    ylab(paste0("CLR ", biotin_feature)) +
    xlab("Condition") +
    theme_minimal(base_size = 14) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      axis.text.x = element_text(angle = 45, hjust = 1)
    )

  if (!is.na(threshold)) {
    p <- p +
      geom_hline(
        yintercept = threshold,
        linetype = "dashed",
        color = "red",
        linewidth = 0.7
      ) +
      annotate(
        "text",
        x = 1.5,
        y = threshold,
        label = paste0("Q", threshold_quantile * 100, " untreated = ", round(threshold, 2)),
        color = "red",
        vjust = -0.5,
        size = 3.5
      )
  }

  save_png(
    p,
    file.path(plot_dir, paste0("cluster_", cluster_id, "_biotin_violin.png")),
    width = 6,
    height = 5
  )
}

# ------------------------------------------------------------------------------
# 7. BIOTIN STATUS SUMMARIES
# ------------------------------------------------------------------------------

metadata <- seurat_object@meta.data %>%
  mutate(
    cluster = as.character(.data[[cluster_column]]),
    condition = as.character(.data[[condition_column]])
  )

summary_all <- metadata %>%
  filter(!is.na(biotin_status)) %>%
  group_by(cluster, biotin_status) %>%
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = biotin_status, values_from = n, values_fill = 0) %>%
  mutate(
    total = positive + negative,
    pct_negative = ifelse(total > 0, 100 * negative / total, NA_real_),
    pct_positive = ifelse(total > 0, 100 * positive / total, NA_real_)
  ) %>%
  arrange(suppressWarnings(as.numeric(cluster)))

summary_treated <- metadata %>%
  filter(condition == treated_label, !is.na(biotin_status)) %>%
  group_by(cluster, biotin_status) %>%
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = biotin_status, values_from = n, values_fill = 0) %>%
  mutate(
    total_treated = positive + negative,
    pct_positive_treated = ifelse(total_treated > 0, 100 * positive / total_treated, NA_real_),
    pct_negative_treated = ifelse(total_treated > 0, 100 * negative / total_treated, NA_real_)
  ) %>%
  arrange(suppressWarnings(as.numeric(cluster)))

summary_untreated <- metadata %>%
  filter(condition == untreated_label, !is.na(biotin_status)) %>%
  group_by(cluster, biotin_status) %>%
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = biotin_status, values_from = n, values_fill = 0) %>%
  mutate(
    total_untreated = positive + negative,
    pct_positive_untreated = ifelse(total_untreated > 0, 100 * positive / total_untreated, NA_real_),
    pct_negative_untreated = ifelse(total_untreated > 0, 100 * negative / total_untreated, NA_real_)
  ) %>%
  arrange(suppressWarnings(as.numeric(cluster)))

summary_combined <- summary_treated %>%
  left_join(
    summary_untreated %>%
      select(cluster, pct_positive_untreated, total_untreated),
    by = "cluster"
  ) %>%
  mutate(
    fold_enrichment = (pct_positive_treated + 0.5) / (pct_positive_untreated + 0.5),
    biotin_delta = pct_positive_treated - pct_positive_untreated
  ) %>%
  arrange(desc(biotin_delta))

write_xlsx(
  list(
    thresholds = threshold_table,
    all_cells = summary_all,
    treated_only = summary_treated,
    untreated_only = summary_untreated,
    combined = summary_combined
  ),
  file.path(summary_dir, "Biotin_pos_neg_summary_per_cluster.xlsx")
)

write.csv(
  summary_combined,
  file.path(summary_dir, "biotin_treated_vs_untreated_summary.csv"),
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 8. PANEL 1G-STYLE SAMPLE-LEVEL BIOTIN DELTA
# ------------------------------------------------------------------------------

sample_level_delta <- metadata %>%
  filter(!is.na(biotin_status)) %>%
  group_by(
    cluster,
    sample = .data[[sample_column]],
    condition,
    biotin_status
  ) %>%
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = biotin_status, values_from = n, values_fill = 0) %>%
  mutate(
    total = positive + negative,
    pct_positive = ifelse(total > 0, 100 * positive / total, NA_real_)
  ) %>%
  select(cluster, sample, condition, pct_positive, total) %>%
  pivot_wider(
    names_from = condition,
    values_from = c(pct_positive, total),
    values_fill = NA
  )

treated_pct_col <- paste0("pct_positive_", treated_label)
untreated_pct_col <- paste0("pct_positive_", untreated_label)

if (all(c(treated_pct_col, untreated_pct_col) %in% colnames(sample_level_delta))) {
  sample_level_delta <- sample_level_delta %>%
    mutate(
      biotin_delta = .data[[treated_pct_col]] - .data[[untreated_pct_col]]
    ) %>%
    arrange(desc(biotin_delta))

  write.csv(
    sample_level_delta,
    file.path(summary_dir, "biotin_delta_sample_level.csv"),
    row.names = FALSE
  )

  selected_delta <- sample_level_delta %>%
    filter(cluster %in% clusters_of_interest)

  p_delta <- ggplot(
    selected_delta,
    aes(x = reorder(cluster, biotin_delta), y = biotin_delta)
  ) +
    geom_col(width = 0.7) +
    coord_flip() +
    labs(
      title = "Biotin delta at sample level",
      subtitle = "Panel 1G provenance: clusters ranked by treated minus untreated Biotin+ percentage",
      x = "Cluster",
      y = "Biotin delta (% positive)"
    ) +
    theme_classic(base_size = 14)

  save_png(
    p_delta,
    file.path(plot_dir, "Delta_Barplot_SampleLevel_SelectedClusters.png"),
    width = 7,
    height = 5
  )
} else {
  message("Skipping sample-level delta plot; treated/untreated sample-level columns were not both found.")
}

# ------------------------------------------------------------------------------
# 9. SELECT CLUSTERS FOR PSEUDOBULK
# ------------------------------------------------------------------------------

eligible_clusters <- summary_combined %>%
  filter(
    total_treated > 0,
    positive >= min_pos_cells_treated,
    pct_positive_treated >= min_pct_pos_treated
  ) %>%
  pull(cluster)

clusters_for_pseudobulk <- intersect(clusters_of_interest, eligible_clusters)

write.csv(
  data.frame(cluster = clusters_for_pseudobulk),
  file.path(dge_dir, "clusters_selected_for_pseudobulk.csv"),
  row.names = FALSE
)

message("Clusters selected for pseudobulk: ", paste(clusters_for_pseudobulk, collapse = ", "))

# ------------------------------------------------------------------------------
# 10. PSEUDOBULK DGE: TREATED BIOTIN+ VS BIOTIN-
# ------------------------------------------------------------------------------

if (run_pseudobulk_dge && length(clusters_for_pseudobulk) > 0) {
  DefaultAssay(seurat_object) <- rna_assay

  rna_counts <- GetAssayData(
    seurat_object,
    assay = rna_assay,
    slot = "counts"
  )

  dge_results <- list()

  for (cluster_id in clusters_for_pseudobulk) {
    message("Running pseudobulk DGE for cluster ", cluster_id)

    meta_cluster <- seurat_object@meta.data %>%
      mutate(cell = rownames(.)) %>%
      filter(
        .data[[cluster_column]] == cluster_id,
        .data[[condition_column]] == treated_label,
        !is.na(biotin_status),
        biotin_status %in% c("negative", "positive")
      )

    if (nrow(meta_cluster) == 0) {
      message("No treated cells with biotin status in cluster ", cluster_id, "; skipping.")
      next
    }

    meta_cluster$sample <- factor(meta_cluster[[sample_column]])
    meta_cluster$biotin_status <- factor(
      meta_cluster$biotin_status,
      levels = c("negative", "positive")
    )

    sample_status_table <- table(meta_cluster$sample, meta_cluster$biotin_status)

    samples_with_both <- rownames(sample_status_table)[
      sample_status_table[, "negative"] > 0 &
        sample_status_table[, "positive"] > 0
    ]

    if (length(samples_with_both) < dge_min_samples_with_both_statuses) {
      message(
        "Fewer than ",
        dge_min_samples_with_both_statuses,
        " samples with both biotin statuses in cluster ",
        cluster_id,
        "; skipping."
      )
      next
    }

    meta_cluster <- meta_cluster %>%
      filter(sample %in% samples_with_both)

    cells_cluster <- meta_cluster$cell

    sub_counts <- rna_counts[, cells_cluster, drop = FALSE]

    group_factor <- interaction(
      meta_cluster$sample,
      meta_cluster$biotin_status,
      drop = TRUE,
      sep = "__"
    )

    pseudobulk_counts <- t(rowsum(t(as.matrix(sub_counts)), group = group_factor))

    group_split <- do.call(
      rbind,
      strsplit(colnames(pseudobulk_counts), "__", fixed = TRUE)
    )

    pheno <- data.frame(
      sample = factor(group_split[, 1]),
      biotin_status = factor(group_split[, 2], levels = c("negative", "positive"))
    )
    rownames(pheno) <- colnames(pseudobulk_counts)

    dge <- DGEList(counts = pseudobulk_counts)

    design <- model.matrix(~ sample + biotin_status, data = pheno)

    keep_genes <- filterByExpr(dge, design = design)
    dge <- dge[keep_genes, , keep.lib.sizes = FALSE]
    dge <- calcNormFactors(dge)

    dge <- estimateDisp(dge, design)
    fit <- glmQLFit(dge, design)
    qlf <- glmQLFTest(fit, coef = "biotin_statuspositive")

    result_table <- topTags(qlf, n = Inf)$table
    result_table$gene <- rownames(result_table)
    result_table$cluster <- cluster_id

    result_table <- result_table %>%
      mutate(
        direction = ifelse(logFC > 0, "up_in_Biotin_pos", "up_in_Biotin_neg"),
        sig_FDR_0.05 = FDR < 0.05,
        sig_FDR_0.10 = FDR < 0.10
      ) %>%
      select(
        cluster,
        gene,
        logFC,
        direction,
        logCPM,
        PValue,
        FDR,
        sig_FDR_0.05,
        sig_FDR_0.10,
        everything()
      )

    sheet_name <- paste0("cluster_", cluster_id)
    dge_results[[sheet_name]] <- result_table

    write.csv(
      result_table,
      file.path(dge_dir, paste0("cluster_", cluster_id, "_edgeR_BiotinPos_vs_Neg.csv")),
      row.names = FALSE
    )

    n_pos <- sum(meta_cluster$biotin_status == "positive")
    n_neg <- sum(meta_cluster$biotin_status == "negative")

    volcano_plot <- EnhancedVolcano(
      result_table,
      lab = result_table$gene,
      x = "logFC",
      y = "PValue",
      pCutoff = volcano_p_cutoff,
      FCcutoff = volcano_fc_cutoff,
      title = paste0("Cluster ", cluster_id, ": Biotin+ vs Biotin-"),
      subtitle = paste0(
        "treated only | Biotin+: ",
        n_pos,
        " cells | Biotin-: ",
        n_neg,
        " cells"
      ),
      pointSize = 1.5,
      labSize = 2.5
    )

    save_png(
      volcano_plot,
      file.path(volcano_dir, paste0("cluster_", cluster_id, "_volcano_BiotinPos_vs_Neg.png")),
      width = 7,
      height = 6
    )
  }

  if (length(dge_results) > 0) {
    write_xlsx(
      dge_results,
      file.path(dge_dir, "pseudobulk_edgeR_results_BiotinPos_vsNeg_treated.xlsx")
    )
  }
}

# ------------------------------------------------------------------------------
# 11. SAVE OBJECT WITH BIOTIN STATUS
# ------------------------------------------------------------------------------

saveRDS(
  seurat_object,
  file.path(output_dir, "seurat_with_biotin_status.rds")
)

message("Done. Outputs saved to: ", output_dir)